### ISSUE TITLE
control dash overflows on divs that are not full screen

### ISSUE THREAD

**Issue by hdngr** [GraphAlchemist/Alchemy#339]
Easy fix:

``` css
.alchemy {
    overflow: hidden;
}
```

e.g. 
![image](https://cloud.githubusercontent.com/assets/1875033/3959273/fc703338-2729-11e4-92f8-3813cb42b1dd.png)
